name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # write is needed for:
      # - OIDC for cosign's use in ecm-distro-tools/publish-image.
      # - Read vault secrets in rancher-eio/read-vault-secrets.
      id-token: write
    
    strategy:
      matrix:
        include:
          - platforms: linux/amd64,linux/arm64
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Publish manifest
      uses: rancher/ecm-distro-tools/actions/publish-image@master
      with:
        image: scanner
        tag: ${{ github.ref_name }}
        platforms: ${{ matrix.platforms }}

        public-registry: docker.io
        public-repo: holyspectral
        public-username: holyspectral
        public-password: ${{ secrets.DOCKER_PASSWORD }}

        #prime-registry: ${{ env.PRIME_REGISTRY }}
        prime-registry: docker.io
        prime-repo: holyspectral
        prime-username: holyspectral
        prime-password: ${{ secrets.PRIME_REGISTRY_PASSWORD }}

          #  publish-assets:
          #    runs-on: ubuntu-latest
          #    permissions:
          #      contents: write # Upload artefacts to release.

          #    steps:
          #    - name: Checkout code
          #      uses: actions/checkout@v4
  
          #    - run: make upload
          #      env:
          #GH_TOKEN: ${{ github.token }}
    # TODO: For experiment only
    - name: Login to registry [Public]
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: holyspectral
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Login to registry [Prime]
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: holyspectral
        password: ${{ secrets.PRIME_REGISTRY_PASSWORD }}
    - name: Retag
      shell: bash
      run: |
        docker buildx imagetools create -t holyspectral/scanner:latest holyspectral/scanner:${{ github.ref_name }}
        docker buildx imagetools create -t holyspectral/scanner:5 holyspectral/scanner:${{ github.ref_name }}
