name: Release

on:
  push:
    tags:
      - 'v*'
env:
  DOCKER_USERNAME: ${{ secrets.NV_DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.NV_DOCKER_PASSWORD }}

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # write is needed for:
      # - OIDC for cosign's use in ecm-distro-tools/publish-image.
      # - Read vault secrets in rancher-eio/read-vault-secrets.
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Parse target tag
      run: |
        TARGET=${{ github.ref_name }}
        echo "TAG=${TARGET#v}" >> $GITHUB_ENV
    - name: Publish neuvector manifest
      uses: holyspectral/ecm-distro-tools/actions/publish-image@use-qemu-8-1-5
      with:
        push-to-public: true
        push-to-prime: false
        image: scanner
        tag: ${{ env.TAG }}
        platforms: linux/amd64,linux/arm64

        public-registry: docker.io
        public-repo: holyspectral
        public-username: ${{ env.DOCKER_USERNAME }}
        public-password: ${{ env.DOCKER_PASSWORD }}
